using Core.Models;
using System.Collections.Generic;

namespace Sklady
{

    class GlobalSettings
    {
        public static bool SeparateAfterFirst = true;
        public static string SyllableSeparator = "-";
       
        public static bool PhoneticsMode = true;
        public static Languages Language = Languages.English;

        public static string LastOpenFolderPath = "";
        public static string LastSaveFolderPath = "";

        public static bool AbsoluteMeasures = false;

        public static CharactersTable CharactersTable = new CharactersTable(Table.Table1);

        public static List<string> CharactersToRemove = new List<string>
            {
                "!",
                ".",
                ",",
                "?",
                "/",
                "\"",
                "\\",
                "”",
                "“",
                "’",
                "'",
                "{",
                "}",
                "[",
                "]",
                "(",
                ")",
                "<",
                ">",
                ";",
                ":",
                "~",
                "`",
                "|",
                "*",
                "@",
                "#",
                "$",
                "%",
                "^",
                "&",
                "+",
                "=",
                "—",
                "_",
                "…",
                "«",
                "»",
                "̑",
                "҂҃",
                "҃",
                "҂",
                "–",
                "„",
                "№",
                "©",
                "‘",
                "°",
                "	",
                "●●●",
                "•",
                "†",
                "∞",
                "■■■",
                "ß",
                "½",
                " ",
                "·",
                "§",
                "¦",
                "œ",
             //   "é",
                //"à",
               // "á",
                //"ü",
               // "ä",
                "č",
                "ö",
                "о́",
                "ơ",
                "®",
                "ô",
                "¥",
                "- -",
                "¬",
                "■",
                "",
                "ý",
                "€",
                "í",
                //"ó",
                "£",
                "€",
                //"ë",
                "™",
                "‹",
                "―",
              //  "ó",
                "ú",
                "−",
                "",
                "♦",
                "�",
                //"ê",
               // "è",
                "ѕ",
                //"ś",
                //"ł",
                //"ę",
                //"ć",
               // "ç",
               // "ż",
                "ў",
                "ñ",
                //"ń",
                "ћ",
                "û",
                "â",
                "å",
                //"ą",
                "њ",
                "´",
                "′",
                "î",
               // "ό",
                "ĵ",
                "æ",
                //"ż",
                "ǿ",
                "►",
                "́н",
                "р́",
                "у́",
                " ь ",
                "љ",
                "›",
                "±",
                "΄",
                "‚",
                "→",
                "ü",
                "٭",
                "●",
                "_",
                "",
                "",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9",
                "0"
            };

        public static List<char> CharsToSkip = new List<char>()
        {

        };
    }
}
